micronaut:
  server:
    port: 8081
  application:
    name: employeeManagement
datasources:
  default:
    url: jdbc:mysql://192.168.126.128:3306/test?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 'root'
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true

netty:
  default:
    allocator:
      max-order: 3
